<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link
        rel="stylesheet"
        href="styles/nav.css" />
</head>

<body>
    <header>
        <div id="logo">
            <a href="#"> Logo</a>
        </div>
        <nav class="navbar">
            <ul>
                <li>
                    <a href="#"> Index </a>
                </li>
                <li>
                    <a href="#"> Sobre nós </a>
                </li>
                <li>
                    <button>Login</button>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <!-- <h1>Layout 1</h1>
        <p>Inclusão da view solicitada</p> -->
        <?php
        // Conteudo da página inserido dinamicamente
        $this->content();
        ?>
    </main>
    <footer>

    </footer>
</body>

</html>